### PR TITLE
Fix ansible-runner-service does not remove hosts from previous runs

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
Bz: https://bugzilla.redhat.com/show_bug.cgi?id=1829214

Signed-off-by: Timothy Asir Jeyasingh <tjeyasin@redhat.com>

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
@pcuzner Please review

**Review by TimothyAsirJeyasing — COMMENTED** [review]
Need to update the issue to point : https://github.com/red-hat-storage/cockpit-ceph-installer/issues/82

**Review by pcuzner — CHANGES_REQUESTED** [review]
You need to include the update to the changed dist modules too please.

**Review by pcuzner — CHANGES_REQUESTED** [review]
this doesn't account for the browser crashing and the user having to re-enter all the hosts again. The fix should relate to populating the hosts state from the current image when the app initially loads

**Review by pcuzner — APPROVED** [review]
LGTM

**Pull request merged**
